@startuml stylesheet

hide circle
hide empty members

skinparam {
  classAttributeIconSize 0
  ' this kind of does not work
  ' groupInheritance 2
  ' #FIXME linetype ortho makes relationship labels invisible!
  ' linetype ortho
  linetype polyline
  monochrome true
  shadowing false
  defaultFontName Consolas
  noteFontName Arial
}

@enduml
