@startuml stylesheet

hide circle
hide empty members

skinparam {
  classAttributeIconSize 0
  ' #FIXME linetype ortho makes relationship labels invisible!
  ' linetype ortho
  linetype polyline
  monochrome true
  defaultFontName Courier
}

@enduml
