@startuml Builder
!include ../style/style.puml

class Director {
  +construct()
}

interface Builder <<interface>> {
  + buildPart(): Builder
}

class ConcreteBuilder {
  +buildPart() : Builder
  +getResult() : void
}

class Product

Director o-right- Builder
ConcreteBuilder .up.|> Builder
ConcreteBuilder .right.> Product

@enduml
