@startuml Iterator
!include ../style/style.puml

class Client

interface Aggregate <<interface>> {
  +createIterator() : Iterator
}

class ConcreteAggregate {
  +createIterator() : Iterator
}

note left of ConcreteAggregate::createIterator()
  return new ConcreteIterator(this)
end note

interface Iterator <<interface>> {
  +first()
  +next()
  +isDone() : bool
  +currentItem()
}

class ConcreteIterator

Client -left-> Aggregate
Client -right-> Iterator

ConcreteAggregate .up.|> Aggregate
ConcreteIterator .up.|> Iterator

ConcreteIterator -left-> ConcreteAggregate
ConcreteAggregate .right.> ConcreteIterator

@enduml
