@startuml Iterator
!include ../style/style.pu

class Client

together {
  interface Aggregate <<interface>> {
    +createIterator() : Iterator
  }

  class ConcreteAggregate {
    +createIterator() : Iterator
  }

  ConcreteAggregate .up.|> Aggregate
}

note left of ConcreteAggregate::createIterator()
  return new ConcreteIterator(this)
end note

together {
  interface Iterator <<interface>> {
    +first()
    +next()
    +isDone() : bool
    +currentItem()
  }

  class ConcreteIterator

  ConcreteIterator .up.|> Iterator
}

Client --> Aggregate
Client --> Iterator

ConcreteIterator -left-> ConcreteAggregate
ConcreteAggregate .right.> ConcreteIterator

@enduml
