@startuml Template Method
!include ../style/style.pu

abstract class AbstractClass {
  +TemplateMethod()
  +PrimitiveOperation1() {abstract}
  #PrimitiveOperation2() {abstract}
  +PostOp1Hook() {abstract}
}

class ConcreteClass {
  +PrimitiveOperation1()
  #PrimitiveOperation2()
}

ConcreteClass -up-|> AbstractClass

note right of AbstractClass::TemplateMethod
  ~...
  PrimitiveOperation1()
  ~...
  PrimitiveOperation2()
  ~...
end note

note left of AbstractClass::PostOp1Hook()
  provides a default empty implementation,
  optionally overridable
end note

note as floatingNote1
  functional programming provides an alternative way
  to implement this pattern!
end note

note as floatingNote2
  hooks placed between methods provide a flexible mechanism
  to extend functionality!
end note

@enduml
