@startuml Template Method
!include ../style/style.pu

abstract class AbstractClass {
  +TemplateMethod()
  +PrimitiveOperation1() {abstract}
  #PrimitiveOperation2() {abstract}
  +PostOp1Hook() {abstract}
}

class ConcreteClass {
  +PrimitiveOperation1()
  #PrimitiveOperation2()
}

ConcreteClass -up-|> AbstractClass

note right of AbstractClass::TemplateMethod
  ~...
  PrimitiveOperation1()
  ~...
  PrimitiveOperation2()
  ~...
end note

note left of AbstractClass::PostOp1Hook()
  provides an optional extension point
  with a default empty implementation.
end note

@enduml
