@startuml Object Adapter
!include ../style/style.pu

class Client

interface Target <<interface>> {
 {abstract} +request()
}

class ObjectAdapter {
  -adaptee : Adaptee
  +request()
}

package "ExternalPackage" {
  class Adaptee {
    +specificRequest()
  }
}
note top
  immutable object that
  needs to be adapted
end note

Client -right-> Target
ObjectAdapter .up.|> Target
ObjectAdapter -right-> Adaptee

@enduml

@startuml Class Adapter
!include ../style/style.pu

class Client

interface Target <<interface>> {
 {abstract} +request()
}

class ClassAdapter {
  +request()
}

package "ExternalPackage" {
  class Adaptee {
    +specificRequest()
  }
}
note top
  immutable object that
  needs to be adapted
end note

Client -right-> Target
ClassAdapter .up.|> Target
ClassAdapter -right-|> Adaptee
note top on link
  since it uses inheritance,
  is less desirable compared
  to the object adapter
end note

@enduml
