@startuml Decorator
!include ../style/style.pu

class Client

interface Component <<interface>> {
  +operation()
}

class ConcreteComponent {
  +operation()
}

abstract class Decorator {
  +operation()
}

class ConcreteDecoratorA {
  -addedState
  +operation()
}

class ConcreteDecoratorB {
  +operation()
  +addedBehavior()
}

Client -right-> Component

Component <|.. ConcreteComponent
Component <|.. Decorator
Component --o Decorator

Decorator <|-- ConcreteDecoratorA
Decorator <|-- ConcreteDecoratorB

note as N1
  component->operation()
end note

N1 -- Decorator::operation

@enduml
