@startuml Decorator
hide circle
hide empty members
skinparam linetype polyline
skinparam classAttributeIconSize 0
skinparam monochrome true

class Client

interface Component <<interface>> {
  +operation()
}

class ConcreteComponent {
  +operation()
}

abstract class Decorator {
  +operation()
}

class ConcreteDecoratorA {
  -addedState
  +operation()
}

class ConcreteDecoratorB {
  +operation()
  +addedBehavior()
}

Client -down-> Component
ConcreteComponent .left.|> Component
Decorator .up.|> Component
Decorator o-up- Component
ConcreteDecoratorA -up-|> Decorator
ConcreteDecoratorB -up-|> Decorator

note right of Decorator::operation
  component->operation()
end note

@enduml
