@startuml Proxy
!include ../style/style.pu

class Client

abstract class Subject {
  {abstract} +request()
}

class RealSubject {
  +request()
}

class Proxy {
  +request()
}

note right of Proxy::request
  realSubject->request()
end note

Client -right-> Subject
RealSubject -up-|> Subject
Proxy -up-|> Subject
Proxy -left-> RealSubject : realSubject
@enduml
